name: smtp.vinasai.ca deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy to Server
        run: |
          set -e

          BACKEND_ENV_B64="$(printf '%s' "${{ vars.BACKEND_ENV }}" | base64 -w0)"
          
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "SERVER_PATH='${{ secrets.WORK_DIR }}' BACKEND_DIR='${{ secrets.WORK_DIR }}' BACKEND_ENV_B64='$BACKEND_ENV_B64' bash -s" << 'EOF'
            set -e

            # Define REPO_URL inside the remote script
            REPO_URL='git@github.com:vinasai/smtp.vinasai.ca.git'

            echo "--- Starting Deployment ---"
            # Ensure the remote SSH known_hosts is set up for github.com
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts

            UPLOADS_DIR="$SERVER_PATH/backend/uploads"
            BACKUP_TAR="/tmp/smtp.vinasai.ca-$(date +%Y%m%d-%H%M%S).tar.gz"
            
            # Perform a fresh clone
            TEMP_CLONE_DIR="/tmp/sakaram-$(date +%s)"
            echo "Cloning repository into $TEMP_CLONE_DIR..."
            
            git clone "$REPO_URL" "$TEMP_CLONE_DIR"
            
            # Replace the old application code
            echo "Updating application code in $SERVER_PATH..."
            rm -rf "$SERVER_PATH"
            mkdir -p "$SERVER_PATH"
            mv "$TEMP_CLONE_DIR"/* "$SERVER_PATH/"
            rm -rf "$TEMP_CLONE_DIR" 
            cd "$BACKEND_DIR"
            
            yarn install --production=false
            echo "Building the application..."

            echo "Writing backend .env..."
            echo "$BACKEND_ENV_B64" | base64 -d > .env
            chmod 600 .env

            pm2 describe smtp.vinasai.ca >/dev/null 2>&1 && pm2 restart smtp.vinasai.ca --update-env || pm2 start npm --name smtp.vinasai.ca -- start
            pm2 save

            # rm -f .env .env.production
            
            echo "--- Deployment Finished Successfully ---"
          EOF
